stages:
  - build
  - stop
  - deploy
variables:
  GO_VERSION: "1.22.3"

# Build stage
build:
  stage: build
  image: golang:${GO_VERSION}
  script:
    - go mod tidy
    - GOOS=linux GOARCH=arm64 go build -o telegram-bot-anime ./
    - echo "Executable built:"
    - ls -lh telegram-bot-anime
  artifacts:
    paths:
      - telegram-bot-anime
    expire_in: 1 hour
  only:
    - main
  except:
    - merge_requests

# Deploy stage (manual trigger only)
stop:
  stage: stop
  script:
    - |
      grep -a 'telegram-bot-anime' /proc/*/cmdline 2>/dev/null
      echo "🔍 Looking for 'telegram-bot-anime' processes..."
      PIDS=$(grep -a 'telegram-bot-anime' /proc/*/cmdline 2>/dev/null | awk -F'/' '/\/proc\/[0-9]+\/cmdline/ {print $3}' | grep -E '^[0-9]+$' | sort -u)
      if [ -n "$PIDS" ]; then
        for pid in $PIDS; do
          if kill "$pid" 2>/dev/null; then
            echo "🛑 telegram-bot-anime stopped (PID: $pid)"
          else
            echo "❌ Failed to stop telegram-bot-anime (PID: $pid)"
          fi
        done
      else
        echo "✅ No running process found for telegram-bot-anime"
      fi
  when: manual
  only:
    - main
  tags:
    - gitlabrunneruser
deploy:
  stage: deploy
  script:
    - echo "Checking available memory..."
    - free -m
    - >
      AVAILABLE_MEM=$(free -m | awk '/^Mem:/{print $7}')
      && echo "Available memory (MB): $AVAILABLE_MEM"
      && MIN_MEM=500
      && if [ "$AVAILABLE_MEM" -lt "$MIN_MEM" ]; then
           echo "Not enough memory to deploy. Need at least $MIN_MEM MB.";
           exit 1;
         fi
    - chmod +x telegram-bot-anime
    - ll || ls
    - pwd || echo "error"
    - echo "Files:"
    - ls -lh
    - echo "🚀 Starting telegram-bot-anime..."
    - nohup ./telegram-bot-anime > output.log 2>&1 &
    - echo $! > bot.pid
    - echo "🚀 Bot started in background with PID $(cat bot.pid)"
  dependencies:
    - build
  needs:
    - job: stop
      optional: false
  when: on_success
  only:
    - main
  tags:
    - gitlabrunneruser  # Runner tag used to run the deploy job
