# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Build executable
        run: |
          go build -o telegram-bot-anime ./
          echo "Executable built:"
          ls -lh telegram-bot-anime

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram-bot-anime
          path: telegram-bot-anime

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'workflow_dispatch'  # Run deploy **only** on manual trigger
    steps:
      - name: Download executable artifact
        uses: actions/download-artifact@v3
        with:
          name: telegram-bot-anime

      - name: Check available memory
        run: |
          echo "Checking available memory..."
          free -m
          AVAILABLE_MEM=$(free -m | awk '/^Mem:/{print $7}')
          echo "Available memory (MB): $AVAILABLE_MEM"
          MIN_MEM=500
          if [ "$AVAILABLE_MEM" -lt "$MIN_MEM" ]; then
            echo "Not enough memory to deploy. Need at least $MIN_MEM MB."
            exit 1
          fi

      - name: Run executable
        run: |
          chmod +x telegram-bot-anime
          echo "🚀 Starting telegram-bot-anime..."
          ./telegram-bot-anime


    # - name: Test
    #   run: go test -v ./...
